### ISSUE TITLE
Aliasing really bad on distant objects

### ISSUE THREAD

**Issue by tylerbobik** [TheShed412/Shedgine#8]
In the new FPS scene, as you move away from the mountains they seem to clip in to each other. For the meterial shader, it seems like we need to play with the depth buffer to fix that.

https://outerra.blogspot.com/2012/11/maximizing-depth-buffer-range-and.html

Implementing this broke stuff, but the clipping was removed so some math stuff needs done similar to a logarithmic depth buffer.

**Comment by TheShed412** [comment]
Fixed this during last session

**Comment by tylerbobik** [comment]
Fixed this in the last session
